
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fws_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - AMBER_SECRET=${AMBER_SECRET}
      - AMBER_YAML=/.fluent/amber.yaml
      - FLUENT_STATE_STORE=/.fluent/state_store
      - FLUENT_CLI_V2_CONFIG_PATH=/.fluent/default_config_test.json
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=system2024!
      - NEO4J_DB=neo4j
    networks:
      - fws_network
    depends_on:
      neo4j:
        condition: service_healthy
      db:
        condition: service_healthy
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/fws_db
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_HOST=neo4j
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    networks:
      - fws_network

  management:
    build:
      context: .
      dockerfile: Dockerfile.management
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./diesel.toml:/app/diesel.toml
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_HOST: db
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - fws_network
    tty: true
    stdin_open: true

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_HOST: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fws_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fws_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/system2024!
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_default__listen__address=0.0.0.0
    volumes:
      - neo4j_data:/data
    networks:
      - fws_network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p system2024! 'MATCH (n) RETURN count(n)' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  neo4j_data:

networks:
  fws_network:
    driver: bridge